### ISSUE TITLE
Missing file "body_models/tpose.npy"

### ISSUE THREAD

**Issue by zhanganny** [g-fiche/VQ-HPS#2]
Hello! The file "body_models/tpose.npy" is missing which is needed during training. How can I get it?

**Comment by g-fiche** [comment]
Hello!

Thank you for pointing that out! I added this file to the upload of checkpoints available [here](https://zenodo.org/records/12771018). You can place the ```tpose.npy``` file in the ```body_models``` folder.

**Comment by zhanganny** [comment]
> Hello!
> 
> Thank you for pointing that out! I added this file to the upload of checkpoints available [here](https://zenodo.org/records/12771018). You can place the `tpose.npy` file in the `body_models` folder.

Great! Thanks~
