### ISSUE TITLE
test result inconsistent

### ISSUE THREAD

**Issue by zhanganny** [g-fiche/VQ-HPS#4]
Hello, I load the released vqhps_hrnet checkpoint to mesh_regressor, and mesh_vqvae_54 to mesh_vqvae. The test results on 3DPW is not as good as the results showed on paper. How can I get it? Is the checkpoint version provided consistent with the paper?
<img width="252" alt="image" src="https://github.com/user-attachments/assets/a17a64a5-56b8-4353-9fa4-6eb5db6ce124">
<img width="1291" alt="image" src="https://github.com/user-attachments/assets/ac034f61-c227-459c-a418-60c27b190e64">

Besides, I also try to train on signle dataset 3DPW, and test on 3DPW, but the result is also inconsistent. All the checkpoints are used to test.（model_best_pampjpe、model_best_v2v and model_checkpoint).

Looking forward to your reply! Thanks so much!

**Comment by g-fiche** [comment]
Hello,

I will not have access to a computer in the next weeks, so I will investigate that when I will be back in office.

For the HRNet test, it might come from the way of selecting joints used to compute the metrics, since the V2V (PVE) matches the test results.

For the second one, it is hard to tell without more information... I will try to find the logs of the training when I have access to my computer.

**Comment by zhanganny** [comment]
> HRNet test, it might come from the way of selecting joints used to compute the metrics,

For the HRNet, the evaluation codes I used is the same as the repo. The way of selecting joints for computing MPJPE and PA-MPJPE is showed below. Is there something wrong?

![image](https://github.com/user-attachments/assets/00bde42d-d73c-4ab4-88dd-964a5cf2e375)

**Comment by zhanganny** [comment]
> Hello,
> 
> I will not have access to a computer in the next weeks, so I will investigate that when I will be back in office.
> 
> For the HRNet test, it might come from the way of selecting joints used to compute the metrics, since the V2V (PVE) matches the test results.
> 
> For the second one, it is hard to tell without more information... I will try to find the logs of the training when I have access to my computer.

Hello, May I ask how you selected joints used to compute the metrics? It's important to me. Thanks a lot. Is there something different with the repo?

**Comment by g-fiche** [comment]
Hello,

As I said yesterday, I am on vacation and do not have access to my computer.

I understand that this is important for you but I cannot do any test in the next weeks, so if you cannot wait until then you can try modifying the way of selecting joints. The most likely would be to remove the [:,:14] everywhere but I am not sure as I cannot test it. Another option would be to use the SMPL 24 joints but I do not think that this is the case.

Thank you for your understanding!

**Comment by zhanganny** [comment]
> 所以如果

OK, I’m sorry to disturb your rest. Wish you a nice holiday~

**Comment by g-fiche** [comment]
No worries, I will keep you updated when I have the solution!

**Comment by g-fiche** [comment]
Hello,

As I suggested a few weeks ago, the gap between the results and the paper came from computing the body joints in the ```mpjpe``` and ```pa_mpjpe``` functions. I just updated them accordingly.

Thanks a lot for pointing this out!

**Comment by zhanganny** [comment]
Hello,

Thanks for your reply! Last week, I removed the [:,:14] as you suggested in the mpjpe and pa_mpjpe functions and tried to test on 3DPW and EMDB separately using the checkpoint with HRNet backbone. There are some questions bothering me:
1. The SOTA methods compared in paper almost use 14 joints for evaluation. The updated version uses 17 joints(pred_joints[:, H36M_TO_J17]) for evaluation will bring performance improvement. Is it still a fare comparison to remove the [:,:14] in the mpjpe and pa_mpjpe functions?
2. I find the results on 3DPW consistent with the paper when removing [:, :14](using 14 joints). But the results on EMDB consistent with the paper when using 17 joints. I'm confused why the evaluation method is not consistent in the same table.

Thanks again for your great work! Looking forward to your reply.

**Comment by zhanganny** [comment]
> Hello,
> 
> As I suggested a few weeks ago, the gap between the results and the paper came from computing the body joints in the `mpjpe` and `pa_mpjpe` functions. I just updated them accordingly.
> 
> Thanks a lot for pointing this out!

last week
