### ISSUE TITLE
Why using different ways for rendering?

### ISSUE THREAD

**Issue by Anny0304** [g-fiche/VQ-HPS#5]
I find there are 2 fuctions for plotting mesh. The function plot_reproj_() takes cameras as input and the function plot_meshes_() not.

Why the two functions use different ways to implement?
1. plot_meshes_() uses pytorch3d.renderer.MeshRenderer for image rendering
2. plot_reproj_() uses pyrender.OffscreenRenderer for image rendering

The results of plot_meshes_() is on left, the one for plot_reproj_() is on right:
<img width="1154" alt="image" src="https://github.com/user-attachments/assets/a769e858-84a4-450a-a16c-4342af268c94">

I find even without camera params as input, the two result seems the same.  

I know this isn't an important part of the whole experiment. But it confused me a lot.

**Comment by g-fiche** [comment]
Hello,

Thank you for your interest in our work!

We estimate the mesh in the camera coordinates; this is why the pose and orientation of the mesh are the same in both visualizations. The estimated camera (used to reproject the mesh on the image) is a weak perspective camera composed of a scale parameter and a 2D translation.

Does that answer your question?
